# -*- coding: utf-8 -*-
"""Projeto02-ED2-Grafos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7xgKlaFJoOh82OB3nN3KABN7U9ZzX_O
"""

import collections

class Grafo:
    def __init__(self, num_vertices):
        # Inicializa o grafo com n vértices usando lista de adjacência
        self.num_vertices = num_vertices
        self.adj = {i: [] for i in range(num_vertices)}

    def adicionar_aresta(self, u, v):
        # Adiciona uma aresta em um grafo não direcionado
        self.adj[u].append(v)
        self.adj[v].append(u)

    def exibir_lista_adjacencia(self):
        # Exibe a representação do grafo
        print("--- Lista de Adjacência ---")
        for vertice in self.adj:
            print(f"{vertice}: {self.adj[vertice]}")
        print("-" * 27)

    def bfs(self, inicio):
        # Busca em Largura (BFS) utilizando fila
        visitados = set()
        fila = collections.deque([inicio])
        ordem_visita = []
        visitados.add(inicio)

        while fila:
            vertice = fila.popleft()
            ordem_visita.append(vertice)
            for vizinho in sorted(self.adj[vertice]):
                if vizinho not in visitados:
                    visitados.add(vizinho)
                    fila.append(vizinho)
        return ordem_visita

    def dfs(self, inicio, visitados=None):
        # Busca em Profundidade (DFS) utilizando recursão
        if visitados is None:
            visitados = []
        ordem_visita = [inicio]
        visitados.append(inicio)
        for vizinho in sorted(self.adj[inicio]):
            if vizinho not in visitados:
                ordem_visita.extend(self.dfs(vizinho, visitados))
        return ordem_visita

    def identificar_componentes_conexas(self):
        # Percorre todos os vértices e identifica componentes
        visitados_global = set()
        componentes = []
        for v in range(self.num_vertices):
            if v not in visitados_global:
                nova_componente = self.dfs_para_componente(v, visitados_global)
                componentes.append(nova_componente)

        for i, comp in enumerate(componentes, 1):
            print(f"Componente {i}: {' '.join(map(str, sorted(comp)))}")
        print(f"Total de componentes: {len(componentes)}")

    def dfs_para_componente(self, v, visitados_global):
        pilha = [v]
        componente_atual = []
        while pilha:
            vertice = pilha.pop()
            if vertice not in visitados_global:
                visitados_global.add(vertice)
                componente_atual.append(vertice)
                for vizinho in self.adj[vertice]:
                    if vizinho not in visitados_global:
                        pilha.append(vizinho)
        return componente_atual

# --- Execução do Teste ---
g = Grafo(10)
arestas = [(0, 1), (1, 2), (2, 3), (4, 5), (6, 7), (7, 8), (8, 6)]
for u, v in arestas:
    g.adicionar_aresta(u, v)

g.exibir_lista_adjacencia()
print(f"Ordem de visita BFS (partindo do 0): {g.bfs(0)}")
print(f"Ordem de visita DFS (partindo do 0): {g.dfs(0)}")
print("\n--- Identificando Componentes Conexas ---")
g.identificar_componentes_conexas()